---

name: Generate artifact tag

on:
  workflow_call:
    secrets:
      BUILD_TAGGING_TOKEN:
        required: true
    outputs:
      tag:
        description: "Artifact tag of current github action run"
        value: "${{ jobs.tag.outputs.output2 }}"

jobs:
  tag:
    name: Generate artifact tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: streetshares/kubernetes
          token: ${{ secrets.BUILD_TAGGING_TOKEN }}
          ref: master
      - uses: fregante/setup-git-user@v1
      - name: Create manifest file
        run: ./scripts/create_manifest_file.sh
      - name: Set output for artifact tag
        run: |
          export ARTIFACT_TAG="$(jq -r '.artifact_version' manifest.json)"
          echo "ARTIFACT_TAG=$ARTIFACT_TAG"
          echo "::set-output name=tag::${ARTIFACT_TAG}"